spring:
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: library-events
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/Jasur/udemy/kafka-for-developers-using-spring-boot/ssl/client.truststore.jks
        trust-store-password: password
        key-store-location: file:/Jasur/udemy/kafka-for-developers-using-spring-boot/ssl/client.keystore.jks
        key-store-password: password
      properties:
        retry-backoff-ms: 1000 # 1 second backoff between retries
        retries: 10 # retry 10 times to produce a failed message
        acks: all # acknowledge leader and all replicas
        security:
            protocol: SSL
    admin:
      properties:
        bootstrap.servers: localhost:992, localhost:9093, localhost:9094